os: linux
dist: trusty
language: cpp

before_install:
 - sudo apt-get update
 - sudo apt-get install -y ubuntu-release-upgrader-core

  # upgrade from Trusty (14.04) to Xenial (16.04)
 - sudo do-release-upgrade --quiet --frontend=DistUpgradeViewNonInteractive
  # upgrade from Xenial (16.04) to Bionic (18.04)
  #sudo do-release-upgrade --quiet --frontend=DistUpgradeViewNonInteractive

  # install packages finally
 - sudo apt-get install -y  git make libtool pkg-config cmake libxml2-dev libprotobuf-dev protobuf-compiler libagg-dev libfreetype6-dev libcairo2-dev libpangocairo-1.0-0 libpango1.0-dev freeglut3 freeglut3-dev qt5-default qtdeclarative5-dev libqt5svg5-dev qtlocation5-dev qtpositioning5-dev qttools5-dev-tools qttools5-dev

install:
 # desktop dependencies (libsailfishapp):
 - git clone https://github.com/sailfish-sdk/libsailfishapp.git dependencies/libsailfishapp
 - cd dependencies/libsailfishapp
 - git checkout tags/0.0.5 -b 0.0.5
 - qmake PREFIX=/usr .
 - make
 - sudo make install
 - cd ../..

before_script: cmake .
script: make
