os: linux
dist: yakkety
language: cpp

before_install:
 - sudo apt-get install -y cmake qt5-qmake qtbase5-dev qtpositioning5-dev
install: 
 - ./scripts/download-dependencies.sh
 - git clone https://github.com/sailfish-sdk/libsailfishapp.git dependencies/libsailfishapp
 - cd dependencies/libsailfishapp
 - mkdir build
 - cd build
 - qmake ..
 - make
 - sudo make install
before_script: cmake .
script: make
