sudo: required
dist: trusty

language: cpp
compiler:
  - clang
  - gcc

cache:
  - apt

branches:
  only:
    - master

os:
  - linux
  - osx

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then (brew update); fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then (brew install protobuf qt5); fi

before_script:
  - . setupAutoconf.sh
  - env
  - pkg-config --list-all | sort
  
script:
  - make full
  - (cd libosmscout/tests && make check)

notifications:
  email:
    recipients:
      - tim@framstag.com
    on_success: change
    on_failure: always

addons:
  apt:
    packages:
    - autoconf
    - pkg-config
    - libxml2-dev
    - libprotobuf-dev
    - protobuf-compiler
    - libagg-dev
    - libfreetype6-dev
    - libcairo2-dev
    - libpangocairo
    - libpango1.0-dev
    - qt5-default
    - qtdeclarative5-dev
    - libqt5svg5-dev
    - qtlocation5-dev
    - freeglut3
    - freeglut3-dev
    - libmarisa-dev

matrix:
  allow_failures:
    - os: osx
