version: '{build}'

branches:
  only:
    - master
    
os: Visual Studio 2015

environment:
  matrix:
  - COMPILER: msys2
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    BIT: 64  

install:
  - set
  - '%APPVEYOR_BUILD_FOLDER%\ci\appveyor\install.bat'
  
build_script:
  - set
  - echo %COMPILER% %MSYS2_ARCH% %MSYS2_DIR% %MSYSTEM% %BIT%
  - echo %PATH%
  - dir C:\%MSYS2_DIR%\%MSYSTEM%\bin
  - dir C:\%MSYS2_DIR%\usr\bin
  
notifications:
  - provider: Email
    to:
      - tim@framstag.com
    on_build_failure: true
    on_build_status_changed: true
          
